# Site settings
title: Societatea Raționalistă Română
email: contact@socrat.ro
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://socratro.github.io"
timezone: Europe/Bucharest
encoding: utf-8

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
