# Site settings
title: Societatea Raționalistă Română
email: contact@socrat.ro
description: >
  SocRat este o organizație non-guvernamentală dedicată promovării și 
  dezvoltării gândirii critice, cunoașterii și educației științifice, 
  scepticismului bazat pe cunoaștere științifică și apărării libertății 
  de exprimare.
url: "http://socratro.github.io"
timezone: Europe/Bucharest
encoding: utf-8
facebook_username: SocRat.ro

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
